[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
leptos = "0.8.20"
leptos_meta = "0.8.6"
leptos_router = "0.8.15"
leptos_axum = { version = "0.8.10", optional = true }

[features]
hydrate = ["leptos/hydrate"]
ssr = ["leptos/ssr", "leptos_meta/ssr", "leptos_router/ssr", "dep:leptos_axum"]
