name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: vault_docs
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      # Dummy secrets
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/vault_docs
      COOKIE_KEY: 8f73644a-ff55-4542-888f-7d8e46253dce-893ccf6f-6e41-45c2-9eda-406e13db4d15
      APP_ENV: development
      COGNITO_REGION: eu-west-2
      COGNITO_USER_POOL_ID: eu-west-2_test
      AWS_COGNITO_CLIENT_ID: test-client-id
      AWS_COGNITO_CLIENT_SECRET: test-client-secret
      COGNITO_DOMAIN: https://test.auth.eu-west-2.amazoncognito.com
      COGNITO_REDIRECT_URI: http://localhost:8080/auth/callback
      COGNITO_LOGOUT_REDIRECT_URI: http://localhost:8080/
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: end2end/package-lock.json

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install cargo-leptos
        run: cargo binstall cargo-leptos -y

      - name: Install e2e deps
        run: |
          cd end2end
          npm ci

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('end2end/package-lock.json') }}

      - name: Install Playwright browsers
        run: |
          cd end2end
          npx playwright install --with-deps chromium firefox

      - name: Build
        run: cargo leptos build --release

      - name: Run unit tests
        run: cargo leptos test

      - name: Run e2e tests
        run: cargo leptos end-to-end --release

      - name: Set image name
        run: echo "IMAGE_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_ENV"

      - name: Build Docker image
        run: docker build -t ghcr.io/${IMAGE_NAME}:${{ github.sha }} .
