name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: end2end/package-lock.json

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install cargo-leptos
        run: cargo binstall cargo-leptos -y

      - name: Install e2e deps
        run: |
          cd end2end
          npm ci

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('end2end/package-lock.json') }}

      - name: Install Playwright browsers
        run: |
          cd end2end
          npx playwright install --with-deps chromium firefox

      - name: Build
        run: cargo leptos build --release

      - name: Run unit tests
        run: cargo leptos test

      - name: Run e2e tests
        run: cargo leptos end-to-end --release

      - name: Set image name
        run: echo "IMAGE_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_ENV"

      - name: Build Docker image
        run: docker build -t ghcr.io/${IMAGE_NAME}:${{ github.sha }} .
